minetest.register_node("literal_trash:disc",{
	description = "Optical Disc",
	drawtype = "signlike",
	tiles = {"literal_trash_disc.png"},
	inventory_image = "literal_trash_disc.png",
	wield_image = "literal_trash_disc.png",
	light_propagates = true,
	sunlight_propagates = true,
	paramtype = "light",
	paramtype2 = "wallmounted",
    
	walkable = false,
	
		
	groups = {choppy = 2},
	selection_box = {
		type = "wallmounted",
	},
})

minetest.register_node("literal_trash:vhs",{
	description = "VHS Tape",
	drawtype = "signlike",
	tiles = {"literal_trash_vhs.png"},
	inventory_image = "literal_trash_vhs.png",
	wield_image = "literal_trash_vhs.png",
	light_propagates = true,
	sunlight_propagates = true,
	paramtype = "light",
	paramtype2 = "wallmounted",
    
	walkable = false,
	
		
	groups = {choppy = 2},
	selection_box = {
		type = "wallmounted",
	},
})

minetest.register_node("literal_trash:bloodstain",{
	description = "Blood Stain",
	drawtype = "signlike",
	tiles = {"literal_trash_bloodstain.png"},
	inventory_image = "literal_trash_bloodstain.png",
	wield_image = "literal_trash_bloodstain.png",
	light_propagates = true,
	sunlight_propagates = true,
	paramtype = "light",
	paramtype2 = "wallmounted",
    
	walkable = false,
	
		
	groups = {choppy = 2},
	selection_box = {
		type = "wallmounted",
	},
})

minetest.register_node("literal_trash:vodka", {
	description = "Vodka Bottle",
	drawtype = "plantlike",
	tiles = {"literal_trash_vodka.png"},
	inventory_image = "literal_trash_vodka.png",
	wield_image = "literal_trash_vodka.png",
	paramtype = "light",
	is_ground_content = false,
	walkable = false,
	selection_box = {
		type = "fixed",
		fixed = {-0.25, -0.5, -0.25, 0.25, 0.3, 0.25}
	},
	groups = {vessel = 1, dig_immediate = 3, attached_node = 1},
	sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("literal_trash:beer_bottle", {
	description = "Beer Bottle",
	drawtype = "plantlike",
	tiles = {"literal_trash_beer_bottle.png"},
	inventory_image = "literal_trash_beer_bottle.png",
	wield_image = "literal_trash_beer_bottle.png",
	paramtype = "light",
	is_ground_content = false,
	walkable = false,
	selection_box = {
		type = "fixed",
		fixed = {-0.25, -0.5, -0.25, 0.25, 0.3, 0.25}
	},
	groups = {vessel = 1, dig_immediate = 3, attached_node = 1},
	sounds = default.node_sound_glass_defaults(),
})

minetest.register_node("literal_trash:beer_bottle_empty", {
	description = "Empty Beer Bottle",
	drawtype = "plantlike",
	tiles = {"literal_trash_beer_bottle_empty.png"},
	inventory_image = "literal_trash_beer_bottle_empty.png",
	wield_image = "literal_trash_beer_bottle_empty.png",
	paramtype = "light",
	is_ground_content = false,
	walkable = false,
	selection_box = {
		type = "fixed",
		fixed = {-0.25, -0.5, -0.25, 0.25, 0.3, 0.25}
	},
	groups = {vessel = 1, dig_immediate = 3, attached_node = 1},
	sounds = default.node_sound_glass_defaults(),
})




minetest.register_node("literal_trash:empty_beer_bottles", {
	description = "Empty Beer Bottles",
	drawtype = "plantlike",
	tiles = {"literal_trash_empty_beer_bottles.png"},
	inventory_image = "literal_trash_empty_beer_bottles.png",
	wield_image = "literal_trash_empty_beer_bottles.png",
	paramtype = "light",
	is_ground_content = false,
	walkable = false,
	selection_box = {
		type = "fixed",
		fixed = {-0.25, -0.5, -0.25, 0.25, 0.3, 0.25}
	},
	groups = {vessel = 1, dig_immediate = 3, attached_node = 1},
	sounds = default.node_sound_defaults(),
})


